CREATE VIEW [Ops].[vCaseMental]
AS 
SELECT 
A.CaseMentalId,
A.CaseId,
A.MentalDressLookupId,
A.MentalHygieneLookupId,
A.MentalBodyTypeLookupId,
A.MentalExpressionLookupId,
A.MentalMotorActivityLookupId,
A.MentalVocabularyLookupId,
A.MentalImpulseControlLookupId,
A.MentalSpeechLookupId,
A.MentalBehaviourLookupId,
A.MentalContentLookupId,
A.MentalFlowOfThoughtLookupId,
A.MentalOrientationLookupId,
A.MentalEstimatedIntellectLookupId,
A.MentalAttentionLookupId,
A.MentalInsightLookupId,
A.MentalJudgementLookupId,
A.MentalMemoryLookupId,
A.MentalInformationLookupId,
A.MentalAbstractionLookupId,

Ops.getMetntalStatusDescription(ISNULL(MentalDressLookupId,''))  as MentalDress,
Ops.getMetntalStatusDescription(ISNULL(MentalHygieneLookupId,''))  as MentalHygiene,
Ops.getMetntalStatusDescription(ISNULL(MentalBodyTypeLookupId,''))  as MentalBodyType,
Ops.getMetntalStatusDescription(ISNULL(MentalExpressionLookupId,''))  as MentalExpression,
Ops.getMetntalStatusDescription(ISNULL(MentalMotorActivityLookupId,''))  as MentalMotorActivity,
Ops.getMetntalStatusDescription(ISNULL(MentalVocabularyLookupId,''))  as MentalVocabulary,
Ops.getMetntalStatusDescription(ISNULL(MentalImpulseControlLookupId,''))  as MentalImpulseControl,
Ops.getMetntalStatusDescription(ISNULL(MentalSpeechLookupId,''))  as MentalSpeech,
Ops.getMetntalStatusDescription(ISNULL(MentalBehaviourLookupId,''))  as MentalBehaviour,
Ops.getMetntalStatusDescription(ISNULL(MentalContentLookupId,''))  as MentalContent,
Ops.getMetntalStatusDescription(ISNULL(MentalFlowOfThoughtLookupId,''))  as MentalFlowOfThought,
Ops.getMetntalStatusDescription(ISNULL(MentalOrientationLookupId,''))  as MentalOrientation,
Ops.getMetntalStatusDescription(ISNULL(MentalEstimatedIntellectLookupId,''))  as MentalEstimatedIntellect,
Ops.getMetntalStatusDescription(ISNULL(MentalAttentionLookupId,''))  as MentalAttention,
Ops.getMetntalStatusDescription(ISNULL(MentalInsightLookupId,''))  as MentalInsight,
Ops.getMetntalStatusDescription(ISNULL(MentalJudgementLookupId,''))  as MentalJudgement,
Ops.getMetntalStatusDescription(ISNULL(MentalMemoryLookupId,''))  as MentalMemory,
Ops.getMetntalStatusDescription(ISNULL(MentalInformationLookupId,''))  as MentalInformation,
Ops.getMetntalStatusDescription(ISNULL(MentalAbstractionLookupId,''))  as MentalAbstraction

FROM [Ops].[trCaseMental] A
