CREATE TABLE [Ops].[trCaseFamilyHouseHold]
(
	[CaseFamilyHouseHoldId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[CaseId] INT NOT NULL,
	ChildrenDeceasedLookupId varchar(100) NULL,
	HouseHoldIncomeLookupId INT NULL,
	SoughtHelpYesNoLookupId INT NULL,
	SoughtHelpDesc varchar(200) NULL,
	SoughtHelpOutPut varchar(200) NULL,
	PeacemakerAssistanceLookupId varchar(100) NULL,
	PeacemakerAssistanceDesc varchar(200),
	PeacemakerFollowupYesNoLookupId INT NULL,
	ClientSignedRegistrationFormYesNoLookupId INT NULL,
	ClientEmailId varchar(200) NULL,
	ReligionLookupId INT NULL,
	LevelOfEducationLookupId INT NULL,
	VocationalSkillsLookupId INT NULL,
	VocationalSkillsDesc varchar(200) NULL,
	OccupationLookupId INT NULL,
	OccupationDesc varchar(200) NULL,
	ClientIncomeLookupId INT NULL,
	HouseHoldMembersLivingLookupId varchar(100) NULL,
	YearsOfMarriage smallint NULL,
	ClientAgeAtFirstChild tinyint NULL
)
